### ISSUE TITLE
after update My virtual flags are not working

### ISSUE THREAD

**Issue by dimpie007** [joleys/niko-home-control-II#117]
After the update of NHC in HA my virtual flags are not working anymor. I have delete them and installed them back but this is still not working. I used them in nodered by using an event state node from HA. 
Last week everything works perfect. 

is there a special way to use the vertual flag in HA. Because the state isn't change in HA by changing the state in NHC. 

Also an NHC plug is not interacting anymore on HA 

This is my error log

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 2 februari 2024 om 23:31:33 (13 occurrences)
Last logged: 08:03:40

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Pause on PRI/Upgrade:

    b''
      ^
```

```
Logger: homeassistant.util.logging
Source: util/logging.py:102
First occurred: 2 februari 2024 om 22:30:29 (221882 occurrences)
Last logged: 09:13:50

Exception in handle_entity_update when dispatching 'nodered_entity_9545350334d6c86c_6236e5c37e8f7536': ({'type': 'nodered/entity', 'server_id': '9545350334d6c86c', 'node_id': '6236e5c37e8f7536', 'state': '9.2 °C', 'attributes': {}, 'id': 15007},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 644, in state numerical_value = float(value) # type:ignore[arg-type] ^^^^^^^^^^^^ ValueError: could not convert string to float: '9.2 °C' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/nodered/__init__.py", line 141, in handle_entity_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state state, attr, capabilities, shadowed_attr = self.__async_calculate_state() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state state = self._stringify_state(available) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state if (state := self.state) is None: ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 646, in state raise ValueError( ValueError: Sensor sensor.nodered_6236e5c37e8f7536 has device class 'temperature', state class 'measurement' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '9.2 °C' (<class 'str'>)
Exception in handle_entity_update when dispatching 'nodered_entity_9545350334d6c86c_6236e5c37e8f7536': ({'type': 'nodered/entity', 'server_id': '9545350334d6c86c', 'node_id': '6236e5c37e8f7536', 'state': '9.2 °C', 'attributes': {}, 'id': 15095},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 644, in state numerical_value = float(value) # type:ignore[arg-type] ^^^^^^^^^^^^ ValueError: could not convert string to float: '9.2 °C' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/nodered/__init__.py", line 141, in handle_entity_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state state, attr, capabilities, shadowed_attr = self.__async_calculate_state() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state state = self._stringify_state(available) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state if (state := self.state) is None: ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 646, in state raise ValueError( ValueError: Sensor sensor.nodered_6236e5c37e8f7536 has device class 'temperature', state class 'measurement' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '9.2 °C' (<class 'str'>)
Exception in handle_entity_update when dispatching 'nodered_entity_9545350334d6c86c_6236e5c37e8f7536': ({'type': 'nodered/entity', 'server_id': '9545350334d6c86c', 'node_id': '6236e5c37e8f7536', 'state': '9.2 °C', 'attributes': {}, 'id': 15184},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 644, in state numerical_value = float(value) # type:ignore[arg-type] ^^^^^^^^^^^^ ValueError: could not convert string to float: '9.2 °C' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/nodered/__init__.py", line 141, in handle_entity_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state state, attr, capabilities, shadowed_attr = self.__async_calculate_state() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state state = self._stringify_state(available) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state if (state := self.state) is None: ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 646, in state raise ValueError( ValueError: Sensor sensor.nodered_6236e5c37e8f7536 has device class 'temperature', state class 'measurement' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '9.2 °C' (<class 'str'>)
Exception in handle_entity_update when dispatching 'nodered_entity_9545350334d6c86c_6236e5c37e8f7536': ({'type': 'nodered/entity', 'server_id': '9545350334d6c86c', 'node_id': '6236e5c37e8f7536', 'state': '9.2 °C', 'attributes': {}, 'id': 15272},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 644, in state numerical_value = float(value) # type:ignore[arg-type] ^^^^^^^^^^^^ ValueError: could not convert string to float: '9.2 °C' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/nodered/__init__.py", line 141, in handle_entity_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state state, attr, capabilities, shadowed_attr = self.__async_calculate_state() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state state = self._stringify_state(available) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state if (state := self.state) is None: ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 646, in state raise ValueError( ValueError: Sensor sensor.nodered_6236e5c37e8f7536 has device class 'temperature', state class 'measurement' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '9.2 °C' (<class 'str'>)
Exception in handle_entity_update when dispatching 'nodered_entity_9545350334d6c86c_6236e5c37e8f7536': ({'type': 'nodered/entity', 'server_id': '9545350334d6c86c', 'node_id': '6236e5c37e8f7536', 'state': '9.2 °C', 'attributes': {}, 'id': 15360},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 644, in state numerical_value = float(value) # type:ignore[arg-type] ^^^^^^^^^^^^ ValueError: could not convert string to float: '9.2 °C' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/nodered/__init__.py", line 141, in handle_entity_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state state, attr, capabilities, shadowed_attr = self.__async_calculate_state() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state state = self._stringify_state(available) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state if (state := self.state) is None: ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 646, in state raise ValueError( ValueError: Sensor sensor.nodered_6236e5c37e8f7536 has device class 'temperature', state class 'measurement' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '9.2 °C' (<class 'str'>)
```

**Comment by tijsverkoyen** [comment]
@dimpie007 The logs you provided are not related to this integration.
In the last upgrade there has not changed anything related to the NHC Virtual flag as I am aware. See: https://github.com/joleys/niko-home-control-II/pull/110

You have removed them and readded them? And the switches are created in Home Assistant? But they never switch on/off, correct? 

If so:
1. Enable debugging for the integration. See https://github.com/joleys/niko-home-control-II?tab=readme-ov-file#i-need-to-see-the-device-list
2. Check your logs for entries like `Name of your flag changed. Topic:  hobby/control/devices/evt | Data: { ... }`

In the data object there should be an element `Status`, with a value of `True` or `False`.

**Comment by tijsverkoyen** [comment]
@dimpie007 any update?

**Comment by dimpie007** [comment]
Problem for flags is solved. Solution was delete the flag in NHC and make a new one. Then reboot home Assistant.
