### ISSUE TITLE
'NoneType' object has no attribute 'loop

### ISSUE THREAD

**Issue by Gavergracht** [joleys/niko-home-control-II#126]
Get this error in the logs....

Traceback (most recent call last):
  File "/config/custom_components/nhc2/nhccoco/coco.py", line 160, in _on_message
    self._device_instances[device[MQTT_DATA_PARAMS_DEVICES_UUID]].on_change(topic, device)
  File "/config/custom_components/nhc2/nhccoco/devices/generic_energyhome.py", line 76, in on_change
    callback()
  File "/config/custom_components/nhc2/entities/generic_energyhome_electrical_power_to_grid.py", line 53, in on_change
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1207, in schedule_update_ha_state
    self.hass.loop.call_soon_threadsafe(self.async_write_ha_state)
    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'loop

**Comment by tijsverkoyen** [comment]
See https://github.com/joleys/niko-home-control-II/issues/98
