### ISSUE TITLE
Fault in logbook  : AttributeError: 'NoneType' object has no attribute 'loop'

### ISSUE THREAD

**Issue by Tjaardv** [joleys/niko-home-control-II#177]
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.nhc2.nhccoco.coco
Bron: custom_components/nhc2/nhccoco/coco.py:186
integratie: Niko Home Control II (documentatie, problemen)
Eerst voorgekomen: 20:52:08 (2 gebeurtenissen)
Laatst gelogd: 20:52:08

'NoneType' object has no attribute 'loop'
Traceback (most recent call last):
  File "/config/custom_components/nhc2/nhccoco/coco.py", line 186, in _on_message
    self._device_instances[device[MQTT_DATA_PARAMS_DEVICES_UUID]].on_change(topic, device)
  File "/config/custom_components/nhc2/nhccoco/devices/device.py", line 167, in on_change
    callback()
  File "/config/custom_components/nhc2/entities/nhc_entity.py", line 21, in on_change
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1231, in schedule_update_ha_state
    self.hass.loop.call_soon_threadsafe(
    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'loop'

this fault is comming back since I 've migrated from my rpi to a proxmox server

**Comment by Tjaardv** [comment]
Solved 

it was an upgrade problem
