### ISSUE TITLE
it is not working 

### ISSUE THREAD

**Issue by itzboterberg** [joleys/niko-home-control-II#178]
hello i setup the nhc2 but it is not working. When i put the integration in debug i get this 

```
Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 4:04:21 AM (1 occurrences)
Last logged: 4:04:21 AM

Detected blocking call to import_module with args ('custom_components.nhc2',) in /usr/src/homeassistant/homeassistant/loader.py, line 1067: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)
```

**Comment by tijsverkoyen** [comment]
Can you enable debug logging. Because this should not be something that blocks the setup, just a warning.

**Comment by itzboterberg** [comment]
that is already on where should I see the logs of it?

**Comment by tijsverkoyen** [comment]
See the first step in https://github.com/joleys/niko-home-control-II?tab=readme-ov-file#i-need-to-see-the-device-list

**Comment by xHuubx** [comment]
I have 4.5.0 and have the same issue, I cleaned all devices and reinstalled NHCII but I also do not get any devices. I see following error: `2024-09-05 14:00:47.250 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fbe082d7950>, '/config/custom_components/nhc2/nhccoco/coco_ca.pem') inside the event loop by custom integration 'nhc2' at custom_components/nhc2/nhccoco/coco.py, line 96: client.tls_set(ca_path) (offender: /usr/local/lib/python3.12/site-packages/paho/mqtt/client.py, line 804: context.load_verify_locations(ca_certs)), please create a bug report at https://github.com/joleys/niko-home-control-II/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
 `

**Comment by tijsverkoyen** [comment]
I find it really hard to believe that you have enabled debugging as described in https://github.com/joleys/niko-home-control-II?tab=readme-ov-file#i-need-to-see-the-device-list

> First you will need to enable debug logging for the integration. You can enable debug logging for this integration by adding the following to your configuration.yaml file:
> 
> ```yaml
> logger:
>   default: warning
>   logs:
>     custom_components.nhc2: debug
> ```
> 
> When this is done you will need to restart Home Assistant. After that you can see the device list in the logs. You can find it by searching for Received device list:. The device list itself is a large JSON string.

Because that would output a lot more data into the logs.

**Comment by xHuubx** [comment]
I did exactly like you asked, I added  `custom_components.nhc2: debug` in my configuration.yaml file.  I do not get anything when I look for `Received device list:` 

![ss1](https://github.com/user-attachments/assets/b6b0607f-01ec-48a7-b3c6-84c688c99454)




If Ilook for NIKO I get:

```
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 09:47:21 (4 occurrences)
Last logged: 09:47:21

Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fac7c9842d0>, '/config/custom_components/nhc2/nhccoco/coco_ca.pem') inside the event loop by custom integration 'nhc2' at custom_components/nhc2/nhccoco/coco.py, line 96: client.tls_set(ca_path) (offender: /usr/local/lib/python3.12/site-packages/paho/mqtt/client.py, line 804: context.load_verify_locations(ca_certs)), please create a bug report at https://github.com/joleys/niko-home-control-II/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/nhc2/__init__.py", line 83, in async_setup_entry coco = CoCo( File "/config/custom_components/nhc2/nhccoco/coco.py", line 96, in __init__ client.tls_set(ca_path)
Detected blocking call to listdir with args ('/config/deps/lib/python3.12/site-packages',) inside the event loop by integration 'twentemilieu' at homeassistant/components/twentemilieu/__init__.py, line 49: await coordinator.async_config_entry_first_refresh() (offender: /usr/local/lib/python3.12/importlib/metadata/__init__.py, line 680: return os.listdir(self.root or '.')), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+twentemilieu%22 For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/twentemilieu/__init__.py", line 49, in async_setup_entry await coordinator.async_config_entry_first_refresh()
Detected blocking call to read_text with args (PosixPath('/usr/local/lib/python3.12/site-packages/twentemilieu-2.0.1.dist-info/METADATA'),) inside the event loop by integration 'twentemilieu' at homeassistant/components/twentemilieu/__init__.py, line 49: await coordinator.async_config_entry_first_refresh() (offender: /usr/local/lib/python3.12/importlib/metadata/__init__.py, line 819: return self._path.joinpath(filename).read_text(encoding='utf-8')), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+twentemilieu%22 For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#read_text Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/twentemilieu/__init__.py", line 49, in async_setup_entry await coordinator.async_config_entry_first_refresh()
Detected blocking call to open with args (PosixPath('/usr/local/lib/python3.12/site-packages/twentemilieu-2.0.1.dist-info/METADATA'),) inside the event loop by integration 'twentemilieu' at homeassistant/components/twentemilieu/__init__.py, line 49: await coordinator.async_config_entry_first_refresh() (offender: /usr/local/lib/python3.12/pathlib.py, line 1027: with self.open(mode='r', encoding=encoding, errors=errors) as f:), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+twentemilieu%22 For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/twentemilieu/__init__.py", line 49, in async_setup_entry await coordinator.async_config_entry_first_refresh()
```

**Comment by nexus256** [comment]
Hi Huub,

At the bottom of the log page in home assistant you will find a button: "Download full log."
Once the log is downloaded, search for the string.

**Comment by xHuubx** [comment]
If I download the complete LOG, I do not get any entries if I look for `Received device list`
Again I am sure added the log details in my config.yaml file.

![config](https://github.com/user-attachments/assets/c95b896a-5b5d-413c-abab-000a23bee290)
![nhc](https://github.com/user-attachments/assets/334ee557-3d19-4377-8365-479be61b0b20)

**Comment by tijsverkoyen** [comment]
Have you restarted Home Assistant after changing the configuration?

**Comment by xHuubx** [comment]
Of course I did

Op vr 6 sep 2024 om 11:00 schreef Tijs Verkoyen ***@***.***>:

**Comment by tijsverkoyen** [comment]
I have just tested with Home Assistant v2024.9.0 and v4.5.0 of this integration. And you should at least see something like below in the logs:

```
[custom_components.nhc2] Connecting to ... with hobby
````

Can you search the full log for `custom_components.nhc2`.
If that is not present I would check if the IP of your Niko Home Assistant Controller is correct and Home Assistant can reach that IP.

**Comment by xHuubx** [comment]
okay, then I get:
Home Assistant Core
```
2024-09-06 09:47:21.309 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.nhc2',) in /usr/src/homeassistant/homeassistant/loader.py, line 1067: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
2024-09-06 09:47:21.533 DEBUG (MainThread) [custom_components.nhc2] Connecting to 192.XXX.XX.XX with hobby
```
I masked the IP myself

**Comment by tijsverkoyen** [comment]
And nothing below it?
Because if so: your controller can't be reached. Remove the integration and readd it with the correct IP and credentials.

**Comment by xHuubx** [comment]
Here a screenshot:

![nhc](https://github.com/user-attachments/assets/14ab0e56-676e-474a-9958-dc272e9d028e)

**Comment by xHuubx** [comment]
I am sure the IP is correct, but I will re-create a hoppy API tonight when I am at home as it will not work remote. I will let you know the outcome. Thanks all for your support so far.

**Comment by tijsverkoyen** [comment]
I don't know how you are running Home Assistant, but check if the Niko Controller can be reached from that machine/docker/...

**Comment by xHuubx** [comment]
Hello Tijs, mistery solved! The IP address changed, strange that if an IP or vice is not reachable that you can add it in HA. 
Thank you all for your patience, and keep up the good work!

**Comment by tijsverkoyen** [comment]
The IP is stored in Home Assistant when the integration is added and configured. I suspect the IP has changed after that.

I would strongly suggest that you make sure the Niko Home Controller has a fixed IP.
