### ISSUE TITLE
'Exception: Connection refused - not authorised' when HA starts

### ISSUE THREAD

**Issue by MirandaPoth** [joleys/niko-home-control-II#20]
This has been working fine until today, when I updated my NIko API token and let the Niko software update do its updates. 
When HA starts, I get the following error in the log:
```2022-08-06 19:09:10 ERROR (Thread-4) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/config/custom_components/nhc2/nhccoco/coco.py", line 124, in _on_connect
    raise Exception(MQTT_RC_CODES[rc])
Exception: Connection refused - not authorised
```
All the Niko devices show in Lovelace but are greyed out. When I click on one to view its details, it says 'This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device.'

I know that the new token is OK and there is nothing wrong with Niko because I can connect to the controller using MQTT Explorer using the same credentials as are in my configuration.yaml. The Niko app on my phone works fine.

This has happened before, and my previous solution (which took days to find!) was to delete the Niko integration from the list of Integrations in the HA Configuration. However, doing this means I have to reallocate all my 84 devices to their correct areas, which I do not want to have to do again.

I have tried the following, in this order, and nothing has made any difference:

- Disabled and reenabled the Niko integration.
- Shutdown the actual server and restarted it. 
- Found the Niko integration in HACS, downloaded new version, restarted HA.
- Updated the Mosquitto broker and restarted the whole machine.
- Unplugged the Niko Ethernet cable for a few minutes then plugged it back in again. 
- Restarted the whole machine again.
- Updated HA from 2022.3.8 to 2022.8.1 and rebooted the host.

I'm wondering if the old API token is cached somewhere in HA or something, but I have no idea how to tell. Or perhaps it's something completely different ...

Any ideas on what might be causing this and/or how I can try to find the problem?

**Comment by MirandaPoth** [comment]
FIXED with the help of petro on the HA Configuration forum, who suggested looking in the .storage folder.

I started looking through the core.* files in .storage, which I found are readble json files. When I got to core.config_entries I found that the password for nhc2 was the old one. Copied & pasted in the new one, saved the file, restarted HA and, lo and behold, everything is working again!
