### ISSUE TITLE
Stop worked in 2022.3.5, HASS os 7.5

### ISSUE THREAD

**Issue by 86hakan** [joleys/niko-home-control-II#3]
The integration has stopped working after update to latest Homeassistant.

I got this in the log.

Logger: root
Source: custom_components/nhc2/nhccoco/coco_climate.py:169
Integration: Niko Home Control II ([documentation](https://github.com/joleys/niko-home-control-II/blob/master/README.md), [issues](https://github.com/joleys/niko-home-control-II))
First occurred: 07:13:56 (1 occurrences)
Last logged: 07:13:56

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3330, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/config/custom_components/nhc2/nhccoco/coco.py", line 88, in _on_message
    self._process_devices_list(response)
  File "/config/custom_components/nhc2/nhccoco/coco.py", line 201, in _process_devices_list
    self.initialize_devices(CoCoDeviceClass.THERMOSTATS, actionable_devices)
  File "/config/custom_components/nhc2/nhccoco/coco.py", line 218, in initialize_devices
    DEVICE_SETS[device_class][INTERNAL_KEY_CLASS](base_device,
  File "/config/custom_components/nhc2/nhccoco/coco_climate.py", line 89, in __init__
    self.update_dev(dev, callback_container)
  File "/config/custom_components/nhc2/nhccoco/coco_climate.py", line 138, in update_dev
    if self._check_for_status_change(dev):
  File "/config/custom_components/nhc2/nhccoco/coco_climate.py", line 169, in _check_for_status_change
    return has_changed
UnboundLocalError: local variable 'has_changed' referenced before assignment

**Comment by joleys** [comment]
Updated my own installation without issues.
Anyone else seeing similar issues with the latest updates?

**Comment by 86hakan** [comment]
Now it´s working again
