### ISSUE TITLE
Uncaught thread exception

### ISSUE THREAD

**Issue by 86hakan** [joleys/niko-home-control-II#39]
After update my integration with niko dont work. I got Uncaught thread exception in logg.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3330, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/config/custom_components/nhc2/nhccoco/coco.py", line 95, in _on_message
    self._process_devices_list(response)
  File "/config/custom_components/nhc2/nhccoco/coco.py", line 216, in _process_devices_list
    self.initialize_devices(CoCoDeviceClass.ENERGYMETERS, actionable_devices)
  File "/config/custom_components/nhc2/nhccoco/coco.py", line 241, in initialize_devices
    self._devices_callback[device_class](self._devices[device_class])
  File "/config/custom_components/nhc2/helpers.py", line 37, in process_entities
    new_entity = obj_create(entity)
  File "/config/custom_components/nhc2/sensor.py", line 30, in <lambda>
    lambda x: NHC2HassEnergyMeter(x))
  File "/config/custom_components/nhc2/sensor.py", line 49, in __init__
    self._state = self._nhc2energymeter.state
  File "/config/custom_components/nhc2/nhccoco/coco_energy.py", line 31, in state
    return self._state
AttributeError: 'CoCoEnergyMeter' object has no attribute '_state' `
I have latest version for niko and homeassistant and i have tried to uninstall and reinstall niko in hacs. But still have the same problem.

**Comment by tijsverkoyen** [comment]
This will be resolved when https://github.com/joleys/niko-home-control-II/pull/49 is merged.

**Comment by tijsverkoyen** [comment]
This is done in the [3.0.0 release](https://github.com/joleys/niko-home-control-II/releases/tag/3.0.0).
