### ISSUE TITLE
NHC2 integration times out after 15-20 minutes

### ISSUE THREAD

**Issue by yannicklips** [joleys/niko-home-control-II#50]
I have a Niko Home Control II installation (for non-bus wiring). Through HomeAssistant and HACS, I have had this integration running for several weeks without any issue (55 devices). All data reports correctly and I can steer the NHC2 components through Home Assistant.

Since a couple of days though, an action in Home Assistant no longer triggers NHC2. Vice versa changing a light via physical button is no reflected in Home Assistant. I cannot pinpoint any software or config update (not in HomeAssistant and not in Niko Home Control II). The hobby API key is still valid.

When I restart the Home Assistant server (docker installation on a Synology NAS), all is working fine for around 15-20 minutes. After that it seems Home Assistant is no longer communicating with the API. Changing a switch in HA then no longer makes a physical difference. Pushing a physical button then no longer changes anything in HA.

I tried uninstalling the integration from HACS, restarted and reinstalled, but the issue remains. In the logbook I cannot find specific errors that point to an issue without NHC2 integration. Several other integrations (myEnergi, SMA, Sonos etc.) remain working fine without any issue, so I am led to believe there is an issue in the connectivity towards NHC2.

Any suggestion on why the connection is stopped after 15-20 minutes?

**Comment by tijsverkoyen** [comment]
My first guess would be that your hub gets disconnected. 
You can enable logging for the integration by adding the following in your configuration.yaml:

````yaml
logger:
  default: warning
  logs:
    custom_components.nhc2: debug
    homeassistant.components.mqtt: debug
````

If the hub gets disconnected a entry will be shown in the log.

**Comment by yannicklips** [comment]
Thanks for the tip, I now see many more steps, it seems to hang on this one:

> 2023-01-24 12:09:00.390 WARNING (Thread-3 (_thread_main)) [custom_components.nhc2.nhccoco.coco] Failed to invoke callback: '1b02693c-2853-4350-a1dd-9fc6dfe6b253'

Any idea what that could mean?

**Comment by tijsverkoyen** [comment]
The `Failed to invoke callback: 'xxxxx'` can be ignored. These mean that a message is published for a device that is not supported in the integration. Has nothing to do with the connection issues.

**Comment by yannicklips** [comment]
Thank you, these are the other custom_components.nhc2 related items.

`2023-01-24 11:45:30.272 DEBUG (MainThread) [custom_components.nhc2] Connecting to 192.168.0.30 with hobby
2023-01-24 11:45:30.458 INFO (Thread-3 (_thread_main)) [custom_components.nhc2.nhccoco.coco] Connected
2023-01-24 11:45:30.568 DEBUG (Thread-3 (_thread_main)) [custom_components.nhc2] Sysinfo: NhcVersion 2.16.2.1 - CocoImage 2021.1-20221109162118
2023-01-24 11:45:30.569 INFO (Thread-3 (_thread_main)) [custom_components.nhc2] Forwarding platform: binary_sensor
2023-01-24 11:45:30.569 INFO (Thread-3 (_thread_main)) [custom_components.nhc2] Forwarding platform: climate
2023-01-24 11:45:30.570 INFO (Thread-3 (_thread_main)) [custom_components.nhc2] Forwarding platform: switch
2023-01-24 11:45:30.570 INFO (Thread-3 (_thread_main)) [custom_components.nhc2] Forwarding platform: light
2023-01-24 11:45:30.570 INFO (Thread-3 (_thread_main)) [custom_components.nhc2] Forwarding platform: fan
2023-01-24 11:45:30.570 INFO (Thread-3 (_thread_main)) [custom_components.nhc2] Forwarding platform: cover
2023-01-24 11:45:30.571 INFO (Thread-3 (_thread_main)) [custom_components.nhc2] Forwarding platform: sensor
2023-01-24 11:45:30.571 INFO (Thread-3 (_thread_main)) [custom_components.nhc2] Forwarding platform: button
2023-01-24 11:45:30.751 DEBUG (MainThread) [custom_components.nhc2.binary_sensor] Platform is starting
2023-01-24 11:45:30.751 DEBUG (MainThread) [custom_components.nhc2.helpers] Processing of nhc2_virtual entities started
2023-01-24 11:45:30.752 DEBUG (MainThread) [custom_components.nhc2.helpers] Active UUIDs: 
2023-01-24 11:45:30.752 DEBUG (MainThread) [custom_components.nhc2.helpers] Existing UUIDs: 
2023-01-24 11:45:30.752 DEBUG (MainThread) [custom_components.nhc2.helpers] New UUIDs: 
2023-01-24 11:45:30.752 DEBUG (MainThread) [custom_components.nhc2.helpers] Adding new entities done.
2023-01-24 11:45:30.752 DEBUG (MainThread) [custom_components.nhc2.helpers] Update done.
2023-01-24 11:45:30.753 DEBUG (MainThread) [custom_components.nhc2.helpers] UUIDs to remove: 
2023-01-24 11:45:30.753 DEBUG (MainThread) [custom_components.nhc2.helpers] Removals done.
2023-01-24 11:45:30.753 DEBUG (MainThread) [custom_components.nhc2.switch] Platform is starting
2023-01-24 11:45:30.753 DEBUG (MainThread) [custom_components.nhc2.helpers] Processing of nhc2_switches entities started
2023-01-24 11:45:30.754 DEBUG (MainThread) [custom_components.nhc2.helpers] Active UUIDs: 
2023-01-24 11:45:30.754 DEBUG (MainThread) [custom_components.nhc2.helpers] Existing UUIDs: 
2023-01-24 11:45:30.754 DEBUG (MainThread) [custom_components.nhc2.helpers] New UUIDs: 1533714d-a044-4a80-8424-111661c9dd29, c60e9fb4-7e8e-4710-9439-835d56384aa1, 31d3bd4e-0f31-4e97-b04d-05c7172a5409, 47565fb4-dcdf-4eb1-9ecf-0155dc0c7f93, 03a0f69c-998e-4223-b676-697185b5ace2, 70d3719b-92f7-457c-b81c-91301cc01997, 2fc49ef5-15a8-49df-964e-b63536dcb8b5, ee37c781-2e9a-4eb0-ad27-352af671a382
2023-01-24 11:45:30.755 DEBUG (MainThread) [custom_components.nhc2.helpers] Adding new entities done.
2023-01-24 11:45:30.755 DEBUG (MainThread) [custom_components.nhc2.helpers] Update done.
2023-01-24 11:45:30.755 DEBUG (MainThread) [custom_components.nhc2.helpers] UUIDs to remove: 
2023-01-24 11:45:30.756 DEBUG (MainThread) [custom_components.nhc2.helpers] Removals done.
2023-01-24 11:45:30.756 DEBUG (MainThread) [custom_components.nhc2.helpers] Processing of nhc2_switches entities started
2023-01-24 11:45:30.757 DEBUG (MainThread) [custom_components.nhc2.helpers] Active UUIDs: 1533714d-a044-4a80-8424-111661c9dd29, c60e9fb4-7e8e-4710-9439-835d56384aa1, 31d3bd4e-0f31-4e97-b04d-05c7172a5409, 47565fb4-dcdf-4eb1-9ecf-0155dc0c7f93, 03a0f69c-998e-4223-b676-697185b5ace2, 70d3719b-92f7-457c-b81c-91301cc01997, 2fc49ef5-15a8-49df-964e-b63536dcb8b5, ee37c781-2e9a-4eb0-ad27-352af671a382
2023-01-24 11:45:30.757 DEBUG (MainThread) [custom_components.nhc2.helpers] Existing UUIDs: 
2023-01-24 11:45:30.757 DEBUG (MainThread) [custom_components.nhc2.helpers] New UUIDs: 
2023-01-24 11:45:30.759 DEBUG (MainThread) [custom_components.nhc2.helpers] Adding new entities done.
2023-01-24 11:45:30.760 DEBUG (MainThread) [custom_components.nhc2.helpers] Update done.
2023-01-24 11:45:30.760 DEBUG (MainThread) [custom_components.nhc2.helpers] UUIDs to remove: 
2023-01-24 11:45:30.760 DEBUG (MainThread) [custom_components.nhc2.helpers] Removals done.
2023-01-24 11:45:30.760 DEBUG (MainThread) [custom_components.nhc2.light] Platform is starting
2023-01-24 11:45:30.761 DEBUG (MainThread) [custom_components.nhc2.helpers] Processing of nhc2_lights entities started
2023-01-24 11:45:30.761 DEBUG (MainThread) [custom_components.nhc2.helpers] Active UUIDs: 
2023-01-24 11:45:30.762 DEBUG (MainThread) [custom_components.nhc2.helpers] Existing UUIDs: 
2023-01-24 11:45:30.762 DEBUG (MainThread) [custom_components.nhc2.helpers] New UUIDs: 4e13df1a-9eca-42f0-a361-a5d037f662f3, 0be652de-845e-4c90-bba3-cae168ac6878, 5e0922e4-00c0-4bdb-ac04-f9c372a0e9f4, f85beef3-bdd5-4ba5-98d5-7cf496cc571c, 36a4defe-38cd-4df7-8f2a-e1309ba877e1, 2a6fec9f-1adf-4419-98a1-942f649a7a1a, 3e62990f-c400-4c00-93cd-a6eee54532bf, 1b899c18-af90-4e7c-9e77-65a84327fd51, 9692ca08-bf76-423d-aabf-2c574f2a666d, d47f7c39-aa65-4c60-b40c-7997bf4d8566, 88bb0efe-12a4-4901-a893-b2aa7eda56ae, a75fac73-46bd-4c4d-b6db-e31cd266cf0b, 03a55fb2-7f5b-43e3-ba4a-f83c4bf557b6, 746888db-c5b1-4ee3-a769-e2059a3a0d81, d7fd1a09-11b4-45a5-a3f9-dd67732763d2, e7fe335c-ebda-444a-a661-62fe6c70dd49, 9e49c273-72b5-4661-bcc0-86cd55dc70cb, 2e5e9b9e-f372-43b0-b404-c2cd2c261242, c1c46097-33d6-44be-a418-481bf5086f3b, e348e006-9c1b-41ed-a61c-3d82dbcbda8e, e508a901-4d63-4a09-a89a-eaf5906ddbbd, 01f2371e-4f5b-487f-95a9-1cac5b2b4607, 5e5d86c1-d6bf-4d68-8cf5-f1b769b5290a, 3936ceb9-ccea-4eac-8ca3-ad7e59203bdf, a83e4852-2a19-44c5-8de7-207dd13d4734, 43e59df8-cf13-402b-8d61-cba5bf1f60b3, 9f89d77d-2077-4ee8-8692-14470ac57160, 0d6a0dc9-05ae-4a8b-b8c0-a7caf5431a37, cffad3fc-444c-4e8f-b253-8c32acac0036, 2fbcfc0e-eb91-45bf-901a-546c0da9b059, 8d90b618-35a7-4a95-8834-376450c0b9d7, 3c2fcddd-64a2-42bc-aa10-6d893b389f78, 65bb44d1-c637-41ef-af21-bd8c435df4a4, cf5a5b83-491a-4dae-b0fd-0f18304486b7
2023-01-24 11:45:30.763 DEBUG (MainThread) [custom_components.nhc2.helpers] Adding new entities done.
2023-01-24 11:45:30.764 DEBUG (MainThread) [custom_components.nhc2.helpers] Update done.
2023-01-24 11:45:30.765 DEBUG (MainThread) [custom_components.nhc2.helpers] UUIDs to remove: 
2023-01-24 11:45:30.765 DEBUG (MainThread) [custom_components.nhc2.helpers] Removals done.
2023-01-24 11:45:30.769 DEBUG (MainThread) [custom_components.nhc2.sensor] Platform is starting
2023-01-24 11:45:30.770 DEBUG (MainThread) [custom_components.nhc2.helpers] Processing of nhc2_energymeters entities started
2023-01-24 11:45:30.770 DEBUG (MainThread) [custom_components.nhc2.helpers] Active UUIDs: 
2023-01-24 11:45:30.770 DEBUG (MainThread) [custom_components.nhc2.helpers] Existing UUIDs: 
2023-01-24 11:45:30.771 DEBUG (MainThread) [custom_components.nhc2.helpers] New UUIDs: 
2023-01-24 11:45:30.771 DEBUG (MainThread) [custom_components.nhc2.helpers] Adding new entities done.
2023-01-24 11:45:30.772 DEBUG (MainThread) [custom_components.nhc2.helpers] Update done.
2023-01-24 11:45:30.773 DEBUG (MainThread) [custom_components.nhc2.helpers] UUIDs to remove: 
2023-01-24 11:45:30.773 DEBUG (MainThread) [custom_components.nhc2.helpers] Removals done.
2023-01-24 11:45:30.773 DEBUG (MainThread) [custom_components.nhc2.helpers] Processing of nhc2_smartplugs entities started
2023-01-24 11:45:30.774 DEBUG (MainThread) [custom_components.nhc2.helpers] Active UUIDs: 
2023-01-24 11:45:30.774 DEBUG (MainThread) [custom_components.nhc2.helpers] Existing UUIDs: 
2023-01-24 11:45:30.775 DEBUG (MainThread) [custom_components.nhc2.helpers] New UUIDs: 54b6cc96-b6c2-45ec-9aaa-dfb31b0a5389, 7c1a793b-ab39-4f71-865d-b494d597a40e, bf0b010e-3d13-4a18-8bd5-06e30d964f38, aba1206a-7038-480f-a3d9-024ab2632c38, 1e081522-2035-429c-b497-971ffeb5209b, 38632a21-733e-45df-967b-93e294235bad, ae00d404-2032-4f95-833e-34b1d0bc7eb2, 575daecb-ea86-49fb-8f25-ff5e46a78134
2023-01-24 11:45:30.776 DEBUG (MainThread) [custom_components.nhc2.helpers] Adding new entities done.
2023-01-24 11:45:30.776 DEBUG (MainThread) [custom_components.nhc2.helpers] Update done.
2023-01-24 11:45:30.776 DEBUG (MainThread) [custom_components.nhc2.helpers] UUIDs to remove: 
2023-01-24 11:45:30.777 DEBUG (MainThread) [custom_components.nhc2.helpers] Removals done.
2023-01-24 11:45:30.777 DEBUG (MainThread) [custom_components.nhc2.button] Platform is starting
2023-01-24 11:45:30.778 DEBUG (MainThread) [custom_components.nhc2.helpers] Processing of nhc2_buttons entities started
2023-01-24 11:45:30.778 DEBUG (MainThread) [custom_components.nhc2.helpers] Active UUIDs: 
2023-01-24 11:45:30.778 DEBUG (MainThread) [custom_components.nhc2.helpers] Existing UUIDs: 
2023-01-24 11:45:30.779 DEBUG (MainThread) [custom_components.nhc2.helpers] New UUIDs: 
2023-01-24 11:45:30.779 DEBUG (MainThread) [custom_components.nhc2.helpers] Adding new entities done.
2023-01-24 11:45:30.779 DEBUG (MainThread) [custom_components.nhc2.helpers] Update done.
2023-01-24 11:45:30.780 DEBUG (MainThread) [custom_components.nhc2.helpers] UUIDs to remove: 
2023-01-24 11:45:30.781 DEBUG (MainThread) [custom_components.nhc2.helpers] Removals done.
2023-01-24 11:45:30.859 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: ipp, binary_sensor.nhc2, switch.nhc2, light.nhc2, sensor.nhc2, button.nhc2
2023-01-24 11:45:31.527 DEBUG (MainThread) [custom_components.nhc2.fan] Platform is starting
2023-01-24 11:45:31.528 DEBUG (MainThread) [custom_components.nhc2.helpers] Processing of nhc2_fans entities started
2023-01-24 11:45:31.528 DEBUG (MainThread) [custom_components.nhc2.helpers] Active UUIDs: 
2023-01-24 11:45:31.528 DEBUG (MainThread) [custom_components.nhc2.helpers] Existing UUIDs: 
2023-01-24 11:45:31.528 DEBUG (MainThread) [custom_components.nhc2.helpers] New UUIDs: 
2023-01-24 11:45:31.529 DEBUG (MainThread) [custom_components.nhc2.helpers] Adding new entities done.
2023-01-24 11:45:31.529 DEBUG (MainThread) [custom_components.nhc2.helpers] Update done.
2023-01-24 11:45:31.529 DEBUG (MainThread) [custom_components.nhc2.helpers] UUIDs to remove: 
2023-01-24 11:45:31.529 DEBUG (MainThread) [custom_components.nhc2.helpers] Removals done.
2023-01-24 11:45:31.551 DEBUG (MainThread) [custom_components.nhc2.climate] Platform is starting
2023-01-24 11:45:31.551 DEBUG (MainThread) [custom_components.nhc2.helpers] Processing of nhc2_thermostats entities started
2023-01-24 11:45:31.551 DEBUG (MainThread) [custom_components.nhc2.helpers] Active UUIDs: 
2023-01-24 11:45:31.551 DEBUG (MainThread) [custom_components.nhc2.helpers] Existing UUIDs: 
2023-01-24 11:45:31.552 DEBUG (MainThread) [custom_components.nhc2.helpers] New UUIDs: 
2023-01-24 11:45:31.552 DEBUG (MainThread) [custom_components.nhc2.helpers] Adding new entities done.
2023-01-24 11:45:31.552 DEBUG (MainThread) [custom_components.nhc2.helpers] Update done.
2023-01-24 11:45:31.552 DEBUG (MainThread) [custom_components.nhc2.helpers] UUIDs to remove: 
2023-01-24 11:45:31.552 DEBUG (MainThread) [custom_components.nhc2.helpers] Removals done.
2023-01-24 11:45:31.620 DEBUG (MainThread) [custom_components.nhc2.cover] Platform is starting
2023-01-24 11:45:31.620 DEBUG (MainThread) [custom_components.nhc2.helpers] Processing of nhc2_covers entities started
2023-01-24 11:45:31.621 DEBUG (MainThread) [custom_components.nhc2.helpers] Active UUIDs: 
2023-01-24 11:45:31.621 DEBUG (MainThread) [custom_components.nhc2.helpers] Existing UUIDs: 
2023-01-24 11:45:31.621 DEBUG (MainThread) [custom_components.nhc2.helpers] New UUIDs: 1f35682a-d288-487f-89f8-90d60d480300, cccfacda-a46e-404b-b7a5-331b165102b8, d7c1bbed-f1a0-4502-9828-b6a787463da8, c9190a47-46bc-4cf6-a7c2-2ab991742525
2023-01-24 11:45:31.621 DEBUG (MainThread) [custom_components.nhc2.helpers] Adding new entities done.
2023-01-24 11:45:31.622 DEBUG (MainThread) [custom_components.nhc2.helpers] Update done.
2023-01-24 11:45:31.622 DEBUG (MainThread) [custom_components.nhc2.helpers] UUIDs to remove: 
2023-01-24 11:45:31.622 DEBUG (MainThread) [custom_components.nhc2.helpers] Removals done.
2023-01-24 11:45:47.411 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform mobile_app is taking over 10 seconds.
2023-01-24 11:45:47.415 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform mobile_app is taking over 10 seconds.
2023-01-24 11:45:47.417 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform mobile_app is taking over 10 seconds.`

Not really seeing a pattern though...

**Comment by tijsverkoyen** [comment]
I lot will be shown in the logs.
But wait for the integration to stop working. I assume there will be a warning with the text "Disconnected".

**Comment by yannicklips** [comment]
Thank you, I monitored live for a while (looking at the Home Assistant interface and seeing power socket consumption slightly vary every couple of seconds).

The issue occurred at 13:32

`2023-01-24 13:32:06.773 ERROR (Thread-3 (_thread_main)) [root] Uncaught thread exception Traceback (most recent call last): File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner self.run() File "/usr/local/lib/python3.10/threading.py", line 953, in run self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main self.loop_forever(retry_first_connection=True) File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever rc = self._loop(timeout) File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1181, in _loop rc = self.loop_write() File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1577, in loop_write rc = self._packet_write() File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2464, in _packet_write write_length = self._sock_send( File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 649, in _sock_send return self._sock.send(buf) File "/usr/local/lib/python3.10/ssl.py", line 1206, in send return self._sslobj.write(data) ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396) 2023-01-24 13:32:18.872 WARNING (MainThread) [pysma] https://192.168.0.37: error detected, closing session to force another login attempt, got: {'err': 401} 2023-01-24 13:32:19.304 ERROR (MainThread) [homeassistant.components.ipp.coordinator] Error fetching ipp data: Invalid response from API: Timeout occurred while connecting to IPP server. 2023-01-24 13:32:19.453 ERROR (MainThread) [homeassistant.components.sma] Error fetching sma data: Error detected while reading `

**Comment by tijsverkoyen** [comment]
`homeassistant.components.sma` is not related to this integration. Probably another integration?

**Comment by yannicklips** [comment]
I was running the complete setup on a Synology DS1512+ with multiple other Docker containers running. At times the memory usage would be rather high (HA around 600MB, but the other Docker containers claiming some as well). As other Dockers became unreliable sometimes as well, I decided to upgrade to a DS1522+ with more available memory.

Since migration and running the exact same Home Assistant configuration, I no longer experienced the issue. Conclusion: most likely a lack of memory, not an issue with this plugin. My apologies for the confusion!
