### ISSUE TITLE
Cover does not work in automations

### ISSUE THREAD

**Issue by 86hakan** [joleys/niko-home-control-II#63]
When i add a cover to an automation as an  action, the only option is to set position and set a value.
The problem is that in version 3.0 the position value doesnt work. The cover doesnt move when i use the position-value and only work with up, down and stop.

**Comment by gesret** [comment]
Bonjour ,
meme probleme, plus aucune automation ne fontionne.  c'est montée ou descente et stop

**Comment by tijsverkoyen** [comment]
Same questions: did it work in the 2.0.0 version? Are your covers supporting setting the position? Can you provide me your device list.
Do you see the publish command in the logs.

From you test.txt file I can see:

`2023-03-30 07:46:03.016 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140696510168128] Entity cover.volet_sejour does not support this service.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity cover.volet_sejour does not support this service.`

But I don't see which service is called.

**Comment by gesret** [comment]
Oui ca fontionnait avec la version 2.
service: cover.set_cover_position.
''Pouvez-vous me fournir votre liste d'appareils'' quelle liste et je la trouve où?
 la commande de publication dans les journauxJ

desole pour mon ignorence

**Comment by tijsverkoyen** [comment]
@gesret for the device list: Could you provide me with your device list so I can debug, see [FAQ → I need to see the device list](https://github.com/joleys/niko-home-control-II#i-need-to-see-the-device-list).

And do you see anything in the logs that looks like: `→ Publishing device control command: ... 'Position': xxx ...` in the logs?

**Comment by tijsverkoyen** [comment]
@gesret or @86hakan I don't own a cover, so it is difficult for me to test. 

From what I can see there should be something in the logs like below when you have set the position of the cover:

```log
[custom_components.nhc2.nhccoco.coco] → Publishing device control command: {"Method": "devices.control", "Params": [{"Devices": [{"Uuid": "8b05788c-6f64-43f6-97f9-b63851230a9d", "Properties": [{"Position": 30}]}]}]}
```

Are you comfortable to edit the code of the integration on your local installation?

There is a file [custom_components/nhc2/nhccoco/devices/motor_action.py](https://github.com/joleys/niko-home-control-II/blob/master/custom_components/nhc2/nhccoco/devices/motor_action.py) which has the following code:

```python
    def set_position(self, gateway, position: int):
        gateway.add_device_control(
            self.uuid,
            PROPERTY_POSITION,
            position
        )
```

I think, this should be changed to:

```python
    def set_position(self, gateway, position: int):
        gateway.add_device_control(
            self.uuid,
            PROPERTY_POSITION,
            str(position)
        )
```

Could you try this and let me know if this works?

**Comment by 86hakan** [comment]
That solved the problem to add str(position) instead of position//Håkan Gundstedt30 mars 2023 kl. 22:40 skrev Tijs Verkoyen ***@***.***>:﻿
@gesret or @86hakan I don't own a cover, so it is difficult for me to test.
From what I can see there should be something in the logs like below when you have set the position of the cover:
[custom_components.nhc2.nhccoco.coco] → Publishing device control command: {"Method": "devices.control", "Params": [{"Devices": [{"Uuid": "8b05788c-6f64-43f6-97f9-b63851230a9d", "Properties": [{"Position": 30}]}]}]}

Are you comfortable to edit the code of the integration on your local installation?
There is a file custom_components/nhc2/nhccoco/devices/motor_action.py which has the following code:
    def set_position(self, gateway, position: int):
        gateway.add_device_control(
            self.uuid,
            PROPERTY_POSITION,
            position
        )
I think, this should be changed to:
    def set_position(self, gateway, position: int):
        gateway.add_device_control(
            self.uuid,
            PROPERTY_POSITION,
            str(position)
        )
Could you try this and let me know if this works?

**Comment by tijsverkoyen** [comment]
I created a release which includes this fix: https://github.com/joleys/niko-home-control-II/releases/tag/v3.0.1

**Comment by gesret** [comment]
Tout est resolu, merci pour la rapidité
