### ISSUE TITLE
NHC2 hub 

### ISSUE THREAD

**Issue by daelderenveld** [joleys/niko-home-control-II#87]
Hello,

Hopefully I am now in the right section to ask a question. I am relatively new to HA and am self-taught rather than full-fledged code writer.

I managed to install the NHCII-integration for via HACS. Now I am running into something that I don't immediately see the reason for. 

I was able to connect to NHC2-HUB via the Wizard via IP-adress, username: hobby and the token provided via the API integration. Then when I go to look after a restart of HA I don't get to see any entities....

In the configuratrian.yaml I manually put the integration below
#Niko home control II
nhc2:
host: 10.0.0.104
username: hobby
password: (the provided token)
port: 8884

any suggestions on what I'm overlooking?

I only see the message below...

![20-09-23 13-44-11](https://github.com/joleys/niko-home-control-II/assets/145501311/bc7963b4-2c6a-44a4-86f9-b45944ff38e7)

I also configured the logger as described below
https://github.com/joleys/niko-home-control-II#i-need-to-see-the-device-list

**Comment by tijsverkoyen** [comment]
And what is the output/content of the devicelist?

**Comment by daelderenveld** [comment]
Can you help me out to explain me where I can visualize this? 
I'm looking in the logbook in HA but I don't thing it's the right place ... 

thx 

Pieter 


Van: "Tijs Verkoyen" ***@***.***> 
Aan: "joleys/niko-home-control-II" ***@***.***> 
Cc: "daelderenveld" ***@***.***>, "Author" ***@***.***> 
Verzonden: Woensdag 20 september 2023 18:42:19 
Onderwerp: Re: [joleys/niko-home-control-II] NHC2 hub (Issue #87) 





And what is the output/content of the devicelist?

**Comment by tijsverkoyen** [comment]
> ## [I need to see the device list](https://github.com/joleys/niko-home-control-II/issues/87#i-need-to-see-the-device-list)
> 
> First you will need to enable debug logging for the integration. You can enable debug logging for this integration by adding the following to your configuration.yaml file:
> 
>     logger:
>       default: warning
>       logs:
>         custom_components.nhc2: debug
> When this is done you will need to restart Home Assistant. After that you can see the device list in the logs. You can find it by searching for `Received device list:`. The device list itself is a large JSON string.

1. Have you restarted Home Assistant
2. Did you check the logs?
3. Did you find the string `Received device list:`

**Comment by daelderenveld** [comment]
in my /config/home-assistant.log I see the following...
Can this be the reason why I do'nt see any entities?

If i need to look for the string "received device list" in which log should I search?

2023-09-23 11:11:14.424 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration nhc2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-23 11:11:14.425 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-23 11:11:21.684 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry configuration.yaml for nhc2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nhc2/__init__.py", line 132, in async_setup_entry
    coco.connect(on_connection_refused)
  File "/config/custom_components/nhc2/nhccoco/coco.py", line 208, in connect
    self._client.connect_async(self._address, self._port)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 979, in connect_async
    if port <= 0:
       ^^^^^^^^^
TypeError: '<=' not supported between instances of 'NoneType' and 'int'

**Comment by tijsverkoyen** [comment]
To me it seems like home assistant is not able to connect to your  Niko Hub

**Comment by daelderenveld** [comment]
Ok, I can do some some network testing to see if there is a connection. Do I need to put something additional in my configuratian.yaml file instead of the following?#Niko home control IInhc2:host: 10.0.0.104username: hobbypassword: (the provided token)port: 8884Op 24 sep. 2023 04:31 schreef Tijs Verkoyen ***@***.***>:
To me it seems like home assistant is not able to connect to your  Niko Hub

**Comment by tijsverkoyen** [comment]
You don’t need to set any configuration for the hub in the yaml files. Configuration is all done when you add the configuration.

**Comment by tibo5150** [comment]
Hello,

I  have the same problem, i can't see any entities after an install the NHCII-integration for via HACS.

I have added the lines in the config files and i have no device list in the log.

Here's my log after restart :

2023-10-02 22:35:33.982 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-02 22:35:33.987 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration nhc2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-02 22:35:53.634 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2023-10-02 22:35:54.631 WARNING (MainThread) [homeassistant.setup] Setup of bluetooth is taking over 10 seconds.
2023-10-02 22:37:25.318 DEBUG (MainThread) [custom_components.nhc2] Connecting to FP00112A233093 with hobby
2023-10-02 22:37:25.327 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: nhc2


I c'ant understand what i'm doing wrong :/

**Comment by tijsverkoyen** [comment]
How did you enter the IP of the hub in the configuration flow? 
Did you enter it manually?

**Comment by tibo5150** [comment]
Thank you for your reply.

Indeed, I had used automatic configuration because the IP address displayed was the correct one.
I just deleted the integration and re-installed it with the "manual" setting, and now I see all my entities!

Many thanks for your help!

**Comment by tijsverkoyen** [comment]
@tibo5150 glad it works.
This is related to https://github.com/joleys/niko-home-control-II/issues/85

**Comment by tijsverkoyen** [comment]
I will close this issue as it goes on in #85
