### ISSUE TITLE
Renson boost switch

### ISSUE THREAD

**Issue by davidvf** [joleys/niko-home-control-II#95]
Hello, i've just added my Renson ventilation into my NHC II setup. 
All the rooms are properly linked to the generic ventilation units in Niko programming software.
From the Niko app, I am able to set the boost for a specific room. 

I noticed that these fans are also added in homeassistant now. I've tried to enable the boost switch, but it doesn't seem to work.

If I enable debug logging for this integration this is the only output i get:
```
2023-11-23 11:04:46.339 DEBUG (Thread-3 (_publish_device_control_commands)) [custom_components.nhc2.nhccoco.coco] → Publishing device control command: {"Method": "devices.control", "Params": [{"Devices": [{"Uuid": "e78be156-7f2c-4d61-8840-a2c02e17fb1e", "Properties": [{"Boost": "True"}]}]}]}
```

If i try the fan entities instead of the boost switches, i get this error:

```
2023-11-23 11:09:48.051 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140563092672704] 'Nhc2GenericFanFanEntity' object has no attribute '_preset_modes'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/nhc2/entities/generic_fan_fan.py", line 93, in async_set_percentage
    self._device.set_fan_speed(self._gateway, percentage_to_ordered_list_item(self._preset_modes, percentage))
                                                                              ^^^^^^^^^^^^^^^^^^
AttributeError: 'Nhc2GenericFanFanEntity' object has no attribute '_preset_modes'
```

Home Assistant version: `2023.11.3`

Let me know if you need any additional output.

**Comment by tijsverkoyen** [comment]
Can you share your device list please. See https://github.com/joleys/niko-home-control-II#i-need-to-see-the-device-list

**Comment by davidvf** [comment]
> Can you share your device list please. See https://github.com/joleys/niko-home-control-II#i-need-to-see-the-device-list

Dropped you an email with the yaml file.

**Comment by tijsverkoyen** [comment]
**First findings:**
* The Renson fans are actually Generic Fans, or "Generic Ventilation Implementation" in the Niko docs.
* The Renson Fan should not have a boost switch. As the boost property is not available. So that should be fixed, although there is a fan speed "boost"

**Way forward**
The `Nhc2GenericFanFanEntity` should be more robust. For instance:
* If the property `Status` is not present it should not be possible to turn off the entity, I don't know if that is possible
* The supported features should be calculated. If FanSpeed is not a range, it should not be possible to set a percentage, but only the possible modes.

**Some questions for you @davidvf :**
1. I suspect you are not able to turn off the ventilation system through Niko or Renson itself? 
2. I suspect there are only 3 modes: Silent, Auto, Boost. Correct?

**Comment by tijsverkoyen** [comment]
@davidvf I have made some changes, which can be seen in https://github.com/joleys/niko-home-control-II/pull/97
Can you apply these changes and let me know if this works?

In your case:
* Boost switch will not be available anymore. 
* Your fan will have an extra dropdown with presets: Silent, Auto, Boost
* Turning off the fan with the switch should not do anything
* Turning off the fan by using the "slider" should change it to Silent
* Switching the mode by using the "slider" should work now. High is boost, Mid is auto, Low is silent, Off is silent

**Comment by tijsverkoyen** [comment]
Thx for your feedback. 
I have created the [v3.3.1](https://github.com/joleys/niko-home-control-II/releases/tag/v3.3.1) release. Which includes the required changes.
